name: Build and Deploy to Azure
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Dependencies for client application.
        working-directory: ./client
        run: npm install

      - name: Run Client Tests
        working-directory: ./client
        run: npm run test

      - name: Build client application.
        working-directory: ./client
        run: npm run build

      - name: Remove .github folder
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./.github

      - name: Remove client folder
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./client

      - name: Remove .idea folder
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./.idea

      - name: Remove .gitignore
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./.gitignore

      - name: Remove README.md
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./README.md

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pawn-shop'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_362BD1D95FE747CA93680EE54A05FF47 }}
          package: .


